### ISSUE TITLE
[Question][M5Stack Core2 IoT] UARTモード でのGPIOアドレスについて

### ISSUE THREAD

**Issue by nagayaoh** [botanicfields/PCB-MBUS-AquesTalk-pico-LSI#1]
### 問い合わせ内容
- ボード動作：　動作中
- ドキュメント内容と実際が異なる
  - ドキュメントではGPIOの割り当ては以下の記載
　　　  - rx: 16
　　　  - tx: 17
  - 環境でSerial2の割り当て(ソースコード)を追ってみると、
　　　  - rx: 13
　　　  - tx: 14
- コメント
  - 動作しているので、パッケージの差異あるいはドキュメント外の仕様かとも思いましたが、念の為確認です。
  - 何か懸念があればフィードバックください

### 環境情報
- Board Ver. : v4
- Pico LSI: ATP3012
- 開発環境: PlatformIO (Core 6.1.11·Home 3.4.4)
　　　- Board: M５Stack Core2
　　　- 確認Package: M5Core2
- ボード ジャンパ設定
　　　- JP1: Close UART-TX
　　　- JP2: Close SPI-MISO
　　　- JP3: Close SPI-SS
　　　- JP4: Close SLEEP ※ 3012だが誤ってCloseしたまま → **何か影響ありますか？**
　　　- JP6: Close Analog Out of ATP3012

#### Serial2 定義
![スクリーンショット 2023-11-21 13 23 02](https://github.com/botanicfields/PCB-MBUS-AquesTalk-pico-LSI/assets/17004575/03094435-be3b-4e59-98db-414669b6ae1c)

#### logical pins
![スクリーンショット 2023-11-21 13 21 51](https://github.com/botanicfields/PCB-MBUS-AquesTalk-pico-LSI/assets/17004575/b82134c9-224e-494d-aeb5-4b588a08969f)

#### map logical pins to GPIO numbers
![スクリーンショット 2023-11-21 13 27 42](https://github.com/botanicfields/PCB-MBUS-AquesTalk-pico-LSI/assets/17004575/8996503d-cbbd-421e-93c9-1b965aefb5d3)

#### 【引用】 Readme.md ジャンパピン
![スクリーンショット 2023-11-21 13 40 21](https://github.com/botanicfields/PCB-MBUS-AquesTalk-pico-LSI/assets/17004575/da916b32-d2dc-4df2-bac1-ae3e3b8352af)

**Comment by uehara00** [comment]
ご指摘ありがとうございます。
当初M5Stack Core1で動作確認し、後日Core2用のサンプルプログラムを追加しましたが、ドキュメントの更新に漏れがありました。ドキュメントを更新いたします。販売中の商品への反映はもうしばらくかかります。

Core1のM-BUSピン配置
https://docs.m5stack.com/en/core/basic_v2.7
Core2のM-BUSピン配置
https://docs.m5stack.com/en/core/core2

**Comment by uehara00** [comment]
シリアルインターフェースのボーレート設定において、ATP3012ではSLEEPは使用しませんが、ATP3012にもSLEEP機能があり本来のSLEEP動作をさせることができます。サンプルプログラムの範囲では特に影響はないと思います。
JP4をOpenにすると、GPIO19(Core1の場合はGPIO13)を他の用途に使える様になります。

ATP3012データシート
https://www.a-quest.com/archive/manual/atp3012_datasheet.pdf

**Comment by uehara00** [comment]
README.mdとdoc/v4/BF-034v4l2_DOC.pdfを更新しました。

**Comment by nagayaoh** [comment]
フィードバックありがとうございます。

確認いたしましたので、本件Closeいたします。
